name: Update URLS
on:
  workflow_dispatch:
jobs:
  updateURLS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ide
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Checkout ide-urls
        uses: actions/checkout@v3
        with:
          repository: devonfw/ide-urls
          path: ide-urls
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and run url updater
        run: |
          cd cli
          mvn -B -ntp -Dstyle.color=always install
          mvn -B -ntp -Dstyle.color=always exec:java -Dexec.mainClass="com.devonfw.tools.ide.url.UpdateInitiator" -Dexec.args="../ide-urls PT5H30M"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ../ide-urls
